spring:
  #  自定义配置文件
  profiles:
    active: prod
  resources:
    static-locations: classpath:/static
  #设置上传文件的最大文件大小
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      #jpa hibernate自动生成表 update不存在创建,存在更新表 create每次执行都创建新的表
      ddl-auto: update
      use-new-id-generator-mappings: false

# 指定全局配置文件
# 指定mapper.xml文件
#mybatis:
#  mapper-locations: classpath*:/mapper/student/*.xml