student:
  name: 333
  age: 33
  sex: 男
  content: name:${student.name},age:${student.age},sex:${student.sex}
server:
  port: 8881
  servlet:
    context-path: /springBootProd
spring:
  #数据库连接
  datasource:
    url: jdbc:oracle:thin:@192.168.48.133:1521:orcl
    username: uecarch
    password: uecarch
    driver-class-name: oracle.jdbc.driver.OracleDriver